@startuml
'<url id="cvt8el13ntnor38nbkdg" type="url" status="parsed" title="Class Diagram syntax and features" wc="35552">https://plantuml.com/class-diagram</url>

package "Third" <<Rectangle>> {
    package "class" <<Rectangle>> {
        class "Class.js"{}
    }
    package "custom"<<Rectangle>> {
        class "sat-js"{}
    }
    package "event" <<Rectangle>> {
        class "EventEmitter" {}
        class "rxjs" <<Rectangle>> {}
    }
    package "json"<<Rectangle>>{
        class "json3" {}
        class "circular-json" {}
    }

    package "log"<<Rectangle>>{
        class "loglevel"{}
    }

    package "modules"<<Rectangle>>{
        class "path-browserify"{}
        class "requirejs"{}
        class "text"{}

        "text" ..> "path-browserify" : 插件
    }
    package "polyfill"<<Rectangle>>{
        class "es5-shim"{}
        class "es6-collections"{}
        class "es6-shim"{}
        class "es7-shim"{}
        class "es2017"{}
    }
    package "stack"{
        class "error-stack-parser"{}
        class "stackframe"{}

        "error-stack-parser" ..> "stackframe" : 依赖
    }
    package "utils"{
        class "linq"{}
        class "lodash"{}
        class "sprintf-js"{}
    }

    package "xml"{
        class "fast-xml-parser"{}
        class "jquery"{}
        class "xmldom"{}
        class "xpath"{}
        class "XUL"{}

        "XUL" ..> "fast-xml-parser" : 依赖
        "XUL" ..> "xmldom" : 依赖
        "XUL" ..> "xpath" : 依赖
        "XUL" ..> "EventEmitter" : 依赖
    }
}

package "Core" <<Rectangle>> {
    package "myShim"<<Rectangle>>{
        class "ErrorDefinitions"{}
        class "FUNC"{}
    }
    package "Object"<<Rectangle>>{
        class "frameRange"{}
        class "frameRangeUtil"{}
        class "moreElement"{}
        class "moreElementUtil"{}
    }
    package "test"<<Rectangle>>{
        class "test-module"{}
    }

    package "Third"<<Rectangle>>{
    }
}





@enduml